### PR TITLE
Move MethodCallInterface and PropertyAssignmentInterface in a sub-namespace

### PR DESCRIPTION
**Pull request by mnapoli**
What do you think of moving those 2 interfaces in a sub namespace ? The root directory is a bit cluttered, and since those two are only related to instance definitions we could move them to a sub namespace ?

### CODE REVIEW

**Comment by moufmouf** [comment]
Agree for the subnamespace :+1: . Warning though, you named the directory "InstanceDefinition". Are we sure that method calls and property assignements will be only performed on "InstanceDefinition" in the end?

For instance, if we add a decorator interface, it will certainly use method calls and property assignments. We could also add those to factories (even if it makes less sense).

Maybe we could come up with a sub-directory with a more generic name, like "Modifiers" (I'm not completely pleased with that idea, but I have no better idea right now....)

**Comment by mnapoli** [comment]
:+1: good catch. `Modifier` or `Action`? I don't see a good name too for now.

**Comment by moufmouf** [comment]
I like 'Action'. :+1:

**Comment by Guillaume-Rossignol** [comment]
Or, maybe : 
- Rename `InstanceDefinitionInterface` => `ServiceDefinitionInterce`
- `MethodCallInterface` =>  `ServiceInitializer/MethodCallInterface` (so, the methodCallInterface is separate from FactoryDefinition)
- `PropertyAssignmentInterface` => `ServiceInitializer/PropertyAssignementInterface`

The wording is more explicit with the purpose and we reduce the possibility of confusion

**Comment by mnapoli** [comment]
It was discussed around a coffee a few minutes ago but +1 with the suggestion above. `Service` is a widespread wording (Symfony, Laravel, Pimple/Silex/Slim, Zend Framework, …) and it would be more explicit. The `ServiceInitializer` namespace then makes even more sense.

**Comment by moufmouf** [comment]
I'm really not a huge fan of the `Service` word because in my opinion, objects stored in a container are not necessarily services. For instance, I could store a Menu and a MenuItem and that are not services.

But I have to agree the "service" word is widespread.

I would go for a :+1:, but really by default. However, I see another problem. The `FactoryDefinitionInterface` is also defining a service, just like the `InstanceDefinitionInterface` is.

All those interfaces are returning services definitions.

The `FactoryDefinitionInterface` is not defining a factory but an instance created via a factory. And the name if somewhat counter-intuitive.

@mnapoli 's code makes clear something is weird:

``` php
$factory = new InstanceDefinition('glide.factory', 'GlideModule\GlideFactory');
$server = new FactoryDefinition('glide', new Reference('glide.factory'), 'create');
```

The `InstanceDefinition` is the actual factory, while the `FactoryDefinition` is the instance based on the factory.

If we want to be explicit (but the naming is very long), we could try something like:
- `InstantiationBasedServiceDefinitionInterface` / `BuiltViaInstantiationServiceDefinitionInterface`
- `FactoryBasedServiceDefinitionInterface` / `BuiltViaFactoryServiceDefinitionInterface`

Or maybe drop the service part which makes:
- `InstantiationBasedDefinitionInterface` / `BuiltViaInstantiationDefinitionInterface`
- `FactoryBasedDefinitionInterface` / `BuiltViaFactoryDefinitionInterface`

Or we could say that creating services using the "new" keyword is standard, and therefore shorten the name. Which would give:
- `ServiceDefinitionInterface`
- `FactoryBasedServiceDefinitionInterface` / `BuiltViaFactoryServiceDefinitionInterface`

Now, there is still a catch... a factory could return something else than a service. An array of services for instance.... So we should drop the "Service" part of the name for the factory.
- `ServiceDefinitionInterface`
- `FactoryBasedDefinitionInterface` / `BuiltViaFactoryDefinitionInterface`

Damn'it! Naming is so hard! Guys, I really don't know what to think...

I'm ok for the `ServiceInitializer` namespace, but what do we do with the `FactoryDefinition` that is a service created via a factory?

**Comment by Guillaume-Rossignol** [comment]
I was thinking that the factoryCall could be a `ServiceInitializer/FactoryCallInterface`. The glide's code will be : 

```
$factory = new InstanceDefinition('glide.factory')->setClassName('GlideModule\GlideFactory');
$server = new InstanceDefinition('glide')->setFactoryCall('glide.factory', 'create');
```

We've got an additionnal object, but we can remove the `FactoryDefinitionInterface` and even when we use a factory, we can set properties or call method on created service (but i'm not sure that it's a real use case). And in container we can't just make a new...

It's a hard problem

**Comment by mnapoli** [comment]
OK we did some thinking again since 20 minutes ago :)

Turns out names currently describe **what the entry is**, except `FactoryDefinition`. And we have come to think that `Service` is a bad name indeed because that describes what the definition will resolve too, and indeed a factory could return a service too… (but it could also return a scalar!)

So:
- `ParameterDefinition`: the entry is a parameter
- `AliasDefinition`: the entry is an alias
- `InstanceDefinition`: the entry is new class instance
- `FactoryCallDefinition`: the entry is a call to a factory

And by the way `ObjectDefinition` would be a bit shorter than instance (and the name is more "common" IMO). Is it better?

**Comment by moufmouf** [comment]
100% :+1:

And :+1: too for `ObjectDefinition`. This completely makes sense.

**Comment by mnapoli** [comment]
OK great, and should we do the `ObjectInitializer` namespace then? I'd say why not.

**Comment by moufmouf** [comment]
It makes sense to me (`Action` was ok too). As you like!

**Comment by mnapoli** [comment]
I have updated the pull request!

**Comment by moufmouf** [comment]
:+1:

**Pull request merged**
