### PR TITLE
Proposal for extending definitions

### PR DESCRIPTION
**Pull request by Anahkiasen**
So, was thinking about extending existing definitions and this is a first stab of how I imagine it could work, considering how it _currently_ works. This adds the ability to set "extensions" on a definition which would be resolved after the main definition is.

Extensions would be definitions of the `ExtendDefinitionInterface` type and would have the same API as `ObjectDefinitionInterface`. This is an example on how to add per example extensions to Twig:

``` php
$twig = new ExtendDefinition(Twig_Environment::class);
$twig->addMethodCalls('addExtension', new Reference(SomeExtension::class));
$twig->addMethodCalls('addGlobal', ['foo' => 'bar']);
$twig->addPropertyAssignment('foo', 'bar');

return [
    $twig,
];
```

Then implementation wise you would just have to append the extensions as they are discovered:

``` php
foreach ($provider->getDefinitions() as $definition) {
    if ($definition instanceof ExtendDefinitionInterface) {
        $this->definitions[$definition->getExtended()]->addExtension($definition);
    } else {
        $this->definitions[$definition->getIdentifier()] = $definition;
    }
}
```

And come resolving time you would loop over the extensions and call their methods/property assignments as is done currently for `ObjectDefinitionInterface`. Made a [test implementation on Glue](https://github.com/madewithlove/glue/blob/feature/definitions-interop/src/Container.php#L108) and it works well as far as I can see:

``` php
// Set properties and call methods
$service = $this->callAssignments($service, $definition);
$service = $this->callMethods($service, $definition);

foreach ($definition->getExtensions() as $extension) {
    $service = $this->callAssignments($service, $extension);
    $service = $this->callMethods($service, $extension);
}
```

---

By binding the extensions to the extended definition itself we would make sure that:
1. You can't extend a service that has no definition (because that would be pointless anyway).
2. Extensions are resolved when the extended service is resolved and don't boot prematurely said service.

This idea most likely has shortcomings which I'm not seeing right now so, input welcome.

### CODE REVIEW

**Comment by moufmouf** [comment]
Hey @Anahkiasen ,

I've been thinking about your proposal a bit, and I like the idea.

I think it solves 80% of the use cases.

Here are 3 use cases that could be problematic though:

1- The definition we are extending must be declared in a container compatible with definition-interop. Compatibility with container-interop containers could be a problem. For instance, if you are providing a twig extension, but if your twig environment is declared in another PSR-11 compatible container (not definition-interop compliant), you cannot easily extend its definition (as I write this, I realise this might be possible by wrapping the PSR-11 container in another container whose sole role would be to extend its definitions). => so this first use case is not really a problem :)

2- There are some cases where we want to provide services, but we don't know who will consume those services. For instance, if you provide a PSR-7 Middleware, you don't know if this middleware will be consumed by Stratigility or whatever other middleware pipe is out there. So we might need a way for provider services to add themselves to an array of services, and for consumers to retrieve this array of services. Maybe we need an ArrayOfServicesDefinition ?

3- There is also a common problem where a service might want to look for any available service implementing an interface. For instance, you might want to create a service that consumes a PSR-3 logger and it would be great if we could have a notion of "default instance" for PSR-3 loggers. We might solve this by convention though (for instance, the identifier of the default service should be the fully qualified interface name)...

What are your thoughts about this?

**Comment by Anahkiasen** [comment]
1) That would be an issue for other things as well but I'm not sure there's much we can do about it, it's the same as using per example a `ReferenceInterface` to a `LoggerInterface`, you have no way to be 100% sure there will be one in the container you're providing the definition for unless you also include a fallback yourself. I however think this is a problem that will be less and less an issue as more containers implement container-interop. The only reason I've ever had two containers hanging around is when one is compatible and the other is not.

2) Not sure I fully get what you're saying, what would the array of services look like?

3) I was actually about to create a separate issue for this :D I think we need a way to have a sort of "bind if" definition, like, "Only bind this service if it wouldn't overwrite an existing one". That way you could bind Monolog but still use any LoggerInterface compatible if there is already one. But to me that's a separate issue at least

**Comment by moufmouf** [comment]
About 2): the problem I'm trying to solve is this:

Just imagine you are writing a PSR-7 middleware. You want this middleware to be registered in the "middleware pipe", which is kind of an array of available middlewares. But you don't know what service will consume this middleware array, so you cannot use `ExtendDefinition` to add your service to the list.

My idea was that `definition-interop` could propose a set of common identifiers for standardized interfaces. In this case, we could simply tell middleware developers to publish their middlewares in the "psr7-middleware" definition. Consumer packages (like Stratigility's MiddlewarePipe) might then consume this array.

This could look like this:

``` php
// Declares an array
interface ArrayDefinitionInterface {
    public function getDefinitions();
}

// This interface is similar to the ExtendDefinitionInterface (it modifies an existing definition), but for arrays.
interface ArrayAddDefinitionModifierInterface {
    // Returns the array definition we want to add things to
    public function getTargetArrayDefinition();

    // Returns the definition to add
    public function getDefinition();
}
```

Note: I just had the idea now, and I'm not sure this is a good idea... especially because Symfony support might be tricky. But this would solve the problem of providing and consuming services on a more generic level. I still need we need your `ExtendDefinition` proposal though. This `ArrayDefinitionInterface` would come additionally, for more complex (and less common) problems.

**Comment by Anahkiasen** [comment]
Yes I understand. My worry is that there will always be new identifiers to add and we can't possibly follow up on them all. I'd rather leave it to package maintainers to specify which key should middlewares be bound to, and let users do the rest. Better would be if we had a `MiddlewareInterface` and all but... I'm afraid that's a separate PSR entierly :D

**Comment by mnapoli** [comment]
Catching up! Just want to say that extending definitions is step 2 of definition-interop, so for me it's not high priority. I'm happy to discuss it though but I think we need more experience with what we already have first, as well as input from framework maintainers.

First I want to say that this is a good approach.

> 1- The definition we are extending must be declared in a container compatible with definition-interop. 

It doesn't have to. We are only defining methods to call on an object. So a definition doesn't have to know about its extensions (nor that I think it should). It requires a little work on the container side: keep "definition extensions" aside, resolve the object first and then apply all extensions on the instance.

> 2- […] So we might need a way for provider services to add themselves to an array of services, and for consumers to retrieve this array of services.

Here we are in the problem of collections/tags. Symfony solves that with tags, Pimple I believe with extensions (i.e. extend the previous entry, which is an array, and add a new item to the array), [PHP-DI with array operations](http://php-di.org/news/15-php-di-5-0-released.html#features-for-modular-applications) (or you can use a decorator like for Pimple), etc.

That solution overlaps a little the "extension" one, but consider those 2 use cases:

``` php
// case 1: we need to call addHandler() for each service (definition extension)
class Logger
{
    public function addHandler(Handler $handler) {}
}

// case 2: we need to pass an array of handlers (collections/tags)
class Logger
{
    public function __construct(array $handlers) {}
}
```

We might need to support both definition extensions _and_ collections/tags.

> 3- There is also a common problem where a service might want to look for any available service implementing an interface. 

I don't understand this one.

**Comment by Anahkiasen** [comment]
Tags are to me really a separate issue and are not necessarily related. I mean while tags _would_ solve this particular use case (Twig extensions) there are a lot of other cases where you might want to extend an existing definition, and providing a simple basic way to do this would ensure it is at least **possible** when the first version of definition-interop ships out, no matter how many tags are supported and all. 

This is something we may need to discuss more in depth but I wouldn't postpone this to a second iteration of definition-interop, I've needed extensions on a lot of projects and currently there is no way around them (what I mean is you can't replicate their behavior with the current feature set, AFAIK)

**Comment by moufmouf** [comment]
Actually, thinking about it, I just realized that you can implement a feature similar to tags using the `ExtendDefinitionInterface` combined with a `FactoryDefinition`.

Lo and behold!

``` php
class Tag {
    private $services = [];

    public function addService($service) {
        $this->services[] = $service;
    }

    public function getServices() {
        return $this->services;
    }
}


class TagFactory {
    public static function getServices(Tag $tag) {
        return $this->tag->getServices();
    }
}
```

Now, let's take Matthieu's second use case:

```
// case 2: we need to pass an array of handlers (collections/tags)
class Logger
{
    public function __construct(array $handlers) {}
}
```

We have this `$handlers` collection. This can be created via an `InstanceDefinition` of the `Tag` class. Let's call this instance the `handlersTag`. Each handler can extend this definition to add itself (using the `addService` method). Then using the `TagFactory::getServices` class (and the `FactoryDefinition`), we can create a container entry that is actually the array of services. We can inject it into the `Logger` constructor. Problem solved!

More importantly, the `Tag` and `TagFactory` are implementation details. They can be provided by a utility library, like Assembly. In short, we don't have to think about a "tag" definition right away, because we can build a similar feature using `ExtendDefinition`.

Actually, it is even better, since we could think about a series of different classes based on the same principle. For instance, one could build a `PriorityQueue` where each service can be added according to a priority index (could be useful for middlewares where a middleware handling an exception/error message might want to be registered before any other)....

The more I think about the `ExtendDefinition`, the more I realize it is powerful (especially when combined with a factory).

I know we told we should keep this for a v2, but I'm starting to wonder if we shouldn't consider adding it right away (or at the very least getting more container developers thinking about it with us... there might be alternatives we did not think about)

**Comment by hannesvdvreken** [comment]
What if you'd like to inject a PSR-3 logger into every object that implements the `Psr\Log\LoggerAwareInterface`. Would that be possible with the `ExtendDefinitionInterface`?

**Comment by Anahkiasen** [comment]
I don't think so no, but then again that wasn't possible with service providers either. Because currently you extend and entry in the container, not really the class itself, that's what allows you to do `new ExtendDefinition('foo.bar')`

**Comment by hannesvdvreken** [comment]
In league/container you could use this: http://container.thephpleague.com/inflectors/
In illuminate/container you could use this: http://laravel.com/docs/5.1/container#container-events

**Comment by Anahkiasen** [comment]
Never knew about this feature, pretty neat. Not sure how we could make ExtendDefinitions both point to any class or a specific entry in the container, how would you imagine that'd work? I had this in mind maybe:

``` php
// Extend multiple services that match instanceof SomeClass
new ExtendDefinition(SomeClass::class);

// Extend a service in particular
new ExtendDefinition(new Reference(SomeClass::class));
new ExtendDefinition(new Reference('foo.bar'))

// This wouldn't do anything since no class would match instanceof "foo.bar"
new ExtendDefinition('foo.bar')
```

Don't know if that doesn't make thing too complicated, what do you think? On the other hand it might actually make the definition more in tune with the other ones since atm it's the only one you don't need to pass a Reference to to point to something

**Comment by mnapoli** [comment]
I don't think think `*Aware` support is the kind of thing needed for module interoperability. It's more at the framework or user level that such thing would be registered. Furthermore it's not a feature supported by all containers.

**Comment by moufmouf** [comment]
@hannesvdvreken I was not aware of those inflectors / container events. Fairly interesting although as @mnapoli stated, this is certainly out of scope for now.

We are really trying to target a small sub-set of all possible features, but a sub-set that is either already available or easy to implement in any container out there.

That being said, I'm very fond of the `ExtendDefinitionInterface` and I think we should work on it and get it in _definition-interop_ quickly. That is clearly a missing piece preventing me to work on a large prototype I've been thinking of (involving a Doctrine DBAL setup, Doctrine cache setup, Symfony console....).

Maybe we should discuss about the name to see if `ExtendDefinitionInterface` is ok or can be improved?

Symfony calls this feature "Decorators" (http://symfony.com/doc/current/components/dependency_injection/advanced.html#decorating-services) I'm not aware what might be the name in other services. @mnapoli : you have such a feature in PHP-DI I think. How did you call it?

**Comment by Anahkiasen** [comment]
In PHP-DI they're called [Decorators](http://php-di.org/doc/definition-overriding.html) as well unless I'm mistaken so maybe that would be more sensible indeed. I don't really like `ExtendDefinition` (was more of a temporary name) as it's only one that describes what it does (extend) as opposed to other definitions who are named after what they are (objects, references, etc)

**Pull request closed without merging**
